server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: order
          uri: http://localhost:8082
          predicates:
            - Path=/orders/**, 
        - id: inventory
          uri: http://localhost:8083
          predicates:
            - Path=/inventories/**, 
        - id: membership
          uri: http://localhost:8084
          predicates:
            - Path=/points/**, 
        - id: delivery
          uri: http://localhost:8085
          predicates:
            - Path=, 
        - id: mypage
          uri: http://localhost:8086
          predicates:
            - Path=, 
        - id: payment
          uri: http://localhost:8087
          predicates:
            - Path=/pays/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: order
          uri: http://order:8080
          predicates:
            - Path=/orders/**, 
        - id: inventory
          uri: http://inventory:8080
          predicates:
            - Path=/inventories/**, 
        - id: membership
          uri: http://membership:8080
          predicates:
            - Path=/points/**, 
        - id: delivery
          uri: http://delivery:8080
          predicates:
            - Path=, 
        - id: mypage
          uri: http://mypage:8080
          predicates:
            - Path=, 
        - id: payment
          uri: http://payment:8080
          predicates:
            - Path=/pays/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
